# Generated by Django 3.0.5 on 2020-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='equipment_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item_collected',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN PROGRESS'), ('CLOSED', 'CLOSED')], max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('EQUIPMENT_AVAILABE', 'EQUIPMENT_AVAILABE'), ('EQUIPMENT_NOT_AVAILABLE', 'EQUIPMENT NOT AVAILABLE'), ('CLOSED', 'CLOSED')], max_length=23),
        ),
    ]
