# Generated by Django 3.0.5 on 2020-04-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200407_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
    ]
