# Generated by Django 3.0.5 on 2020-04-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200408_1502'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
            ],
        ),
    ]
